import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/custom/Navbar";
import { Footer } from "@/components/custom/Footer";
import { getGlobalPageData } from "@/data/loader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const globalData = await getGlobalPageData();
  const { header, footer } = globalData;
  return (
    <html lang="en" className="scroll-smooth">
      <body className={`antialiased ${inter.className}`}>
        <Navbar data={header} />
        <main>{children}</main>
        <Footer data={footer} />
      </body>
    </html>
  );
}
